# Generated by Django 5.2.4 on 2026-03-04 08:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("documents", "0003_workspace_asset_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Handbook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ISO9001", "ISO 9001"),
                            ("ISO14001", "ISO 14001"),
                            ("ISO45001", "ISO 45001"),
                            ("SCC_STAR", "SCC*"),
                            ("SCC_DOUBLESTAR", "SCC**"),
                            ("SCCP", "SCCP"),
                            ("SCP", "SCP"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_PROGRESS", "In Progress"),
                            ("READY", "Ready"),
                            ("EXPORTED", "Exported"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("root_storage_path", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handbooks",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "db_table": "documents_handbook",
            },
        ),
        migrations.CreateModel(
            name="HandbookFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("path_in_handbook", models.TextField()),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("DOCX", "DOCX"),
                            ("PPTX", "PPTX"),
                            ("XLSX", "XLSX"),
                            ("OTHER", "OTHER"),
                        ],
                        default="OTHER",
                        max_length=8,
                    ),
                ),
                ("original_blob_ref", models.TextField()),
                ("working_blob_ref", models.TextField(blank=True, default="")),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PARSED", "Parsed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("checksum", models.CharField(blank=True, default="", max_length=64)),
                ("size", models.BigIntegerField(default=0)),
                ("mime", models.CharField(blank=True, default="", max_length=255)),
                ("placeholder_total", models.IntegerField(default=0)),
                ("placeholder_resolved", models.IntegerField(default=0)),
                ("parse_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "handbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="documents.handbook",
                    ),
                ),
            ],
            options={
                "db_table": "documents_handbook_file",
            },
        ),
        migrations.CreateModel(
            name="Placeholder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[("TEXT", "Text"), ("ASSET", "Asset")], max_length=8
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("occurrences", models.IntegerField(default=0)),
                ("meta", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "handbook_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placeholders",
                        to="documents.handbookfile",
                    ),
                ),
            ],
            options={
                "db_table": "documents_placeholder",
            },
        ),
        migrations.CreateModel(
            name="PlaceholderValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value_text", models.TextField(blank=True, null=True)),
                ("asset_id", models.UUIDField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("AI", "AI"),
                            ("IMPORTED", "Imported"),
                        ],
                        default="MANUAL",
                        max_length=16,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "handbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placeholder_values",
                        to="documents.handbook",
                    ),
                ),
            ],
            options={
                "db_table": "documents_placeholder_value",
            },
        ),
        migrations.CreateModel(
            name="VersionSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.IntegerField()),
                ("manifest", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "handbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="documents.handbook",
                    ),
                ),
            ],
            options={
                "db_table": "documents_version_snapshot",
            },
        ),
        migrations.AddIndex(
            model_name="handbook",
            index=models.Index(
                fields=["customer", "created_at"], name="docs_h_cust_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="handbook",
            index=models.Index(
                fields=["status", "updated_at"], name="docs_h_status_updated_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="handbookfile",
            index=models.Index(
                fields=["handbook", "parse_status"], name="docs_hf_hb_parse_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="handbookfile",
            index=models.Index(
                fields=["handbook", "path_in_handbook"], name="docs_hf_hb_path_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="handbookfile",
            constraint=models.UniqueConstraint(
                fields=("handbook", "path_in_handbook"),
                name="documents_handbook_file_unique_path",
            ),
        ),
        migrations.AddIndex(
            model_name="placeholder",
            index=models.Index(
                fields=["handbook_file", "kind"], name="docs_p_file_kind_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="placeholder",
            constraint=models.UniqueConstraint(
                fields=("handbook_file", "key"),
                name="documents_placeholder_file_key_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="placeholdervalue",
            index=models.Index(
                fields=["handbook", "updated_at"], name="docs_pv_hb_updated_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="placeholdervalue",
            constraint=models.UniqueConstraint(
                fields=("handbook", "key"),
                name="documents_placeholder_value_unique_key",
            ),
        ),
        migrations.AddIndex(
            model_name="versionsnapshot",
            index=models.Index(
                fields=["handbook", "-version_number"], name="docs_vs_hb_ver_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="versionsnapshot",
            constraint=models.UniqueConstraint(
                fields=("handbook", "version_number"),
                name="documents_snapshot_unique_version",
            ),
        ),
    ]
