# Generated by Django 5.2.4 on 2026-03-07 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_placeholder_parse_cache"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placeholdervalue",
            name="source",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("AI", "AI"),
                    ("IMPORTED", "Imported"),
                    ("COMPOSED", "Composed"),
                ],
                default="MANUAL",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="DocumentTextExtractionCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checksum", models.CharField(max_length=64)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("DOCX", "DOCX"),
                            ("PPTX", "PPTX"),
                            ("XLSX", "XLSX"),
                            ("TXT", "TXT"),
                            ("MD", "MD"),
                            ("PDF", "PDF"),
                            ("OTHER", "OTHER"),
                        ],
                        max_length=8,
                    ),
                ),
                ("normalized_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "documents_text_extraction_cache",
                "indexes": [
                    models.Index(
                        fields=["file_type", "-updated_at"],
                        name="docs_tec_type_updated_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("checksum", "file_type"),
                        name="docs_text_extract_cache_unique_checksum_type",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlaceholderGenerationAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("quick_fill", "Quick Fill"), ("compose", "Compose")],
                        max_length=16,
                    ),
                ),
                ("instruction", models.TextField(blank=True, default="")),
                (
                    "output_style",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("language", models.CharField(blank=True, default="", max_length=16)),
                ("model", models.CharField(blank=True, default="", max_length=128)),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                ("references_used", models.JSONField(default=list)),
                ("file_context_used", models.JSONField(default=dict)),
                (
                    "fallback_path",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("trace", models.JSONField(default=dict)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "handbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_audits",
                        to="documents.handbook",
                    ),
                ),
                (
                    "handbook_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_audits",
                        to="documents.handbookfile",
                    ),
                ),
                (
                    "placeholder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_audits",
                        to="documents.placeholder",
                    ),
                ),
            ],
            options={
                "db_table": "documents_placeholder_generation_audit",
            },
        ),
        migrations.AddField(
            model_name="placeholdervalue",
            name="last_generation_audit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applied_values",
                to="documents.placeholdergenerationaudit",
            ),
        ),
        migrations.CreateModel(
            name="ReferenceDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("DOCX", "DOCX"),
                            ("PPTX", "PPTX"),
                            ("XLSX", "XLSX"),
                            ("TXT", "TXT"),
                            ("MD", "MD"),
                            ("PDF", "PDF"),
                            ("OTHER", "OTHER"),
                        ],
                        default="OTHER",
                        max_length=8,
                    ),
                ),
                ("mime_type", models.CharField(blank=True, default="", max_length=255)),
                ("storage_path", models.TextField()),
                ("normalized_storage_path", models.TextField(blank=True, default="")),
                ("checksum", models.CharField(blank=True, default="", max_length=64)),
                ("size_bytes", models.BigIntegerField(default=0)),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PARSED", "Parsed"),
                            ("UNSUPPORTED", "Unsupported"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("parse_error", models.TextField(blank=True, default="")),
                ("summary", models.TextField(blank=True, default="")),
                ("section_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "handbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_documents",
                        to="documents.handbook",
                    ),
                ),
            ],
            options={
                "db_table": "documents_reference_document",
            },
        ),
        migrations.CreateModel(
            name="ReferenceChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ordinal", models.IntegerField()),
                ("chunk_type", models.CharField(max_length=32)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("locator", models.JSONField(default=dict)),
                ("content", models.TextField()),
                ("content_hash", models.CharField(max_length=64)),
                ("estimated_tokens", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reference_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="documents.referencedocument",
                    ),
                ),
            ],
            options={
                "db_table": "documents_reference_chunk",
            },
        ),
        migrations.CreateModel(
            name="ReferenceDocumentLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("handbook", "Handbook"),
                            ("file", "File"),
                            ("placeholder", "Placeholder"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "handbook_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_links",
                        to="documents.handbookfile",
                    ),
                ),
                (
                    "placeholder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_links",
                        to="documents.placeholder",
                    ),
                ),
                (
                    "reference_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="documents.referencedocument",
                    ),
                ),
            ],
            options={
                "db_table": "documents_reference_document_link",
            },
        ),
        migrations.AddIndex(
            model_name="placeholdergenerationaudit",
            index=models.Index(
                fields=["handbook", "-created_at"], name="docs_pga_hb_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="placeholdergenerationaudit",
            index=models.Index(
                fields=["handbook_file", "-created_at"],
                name="docs_pga_file_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="placeholdergenerationaudit",
            index=models.Index(
                fields=["placeholder", "-created_at"], name="docs_pga_pl_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referencedocument",
            index=models.Index(
                fields=["handbook", "-created_at"], name="docs_rd_hb_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referencedocument",
            index=models.Index(
                fields=["handbook", "parse_status"], name="docs_rd_hb_parse_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referencechunk",
            index=models.Index(
                fields=["reference_document", "ordinal"], name="docs_rc_doc_ordinal_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referencechunk",
            index=models.Index(
                fields=["content_hash"], name="docs_rc_content_hash_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="referencechunk",
            constraint=models.UniqueConstraint(
                fields=("reference_document", "ordinal"),
                name="docs_reference_chunk_unique_ordinal",
            ),
        ),
        migrations.AddIndex(
            model_name="referencedocumentlink",
            index=models.Index(
                fields=["reference_document", "scope"], name="docs_rdl_doc_scope_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referencedocumentlink",
            index=models.Index(
                fields=["handbook_file", "scope"], name="docs_rdl_file_scope_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referencedocumentlink",
            index=models.Index(
                fields=["placeholder", "scope"], name="docs_rdl_placeholder_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="referencedocumentlink",
            constraint=models.UniqueConstraint(
                fields=("reference_document", "scope", "handbook_file", "placeholder"),
                name="docs_reference_link_unique_target",
            ),
        ),
    ]
